Remove `-v` flag from govendor sync
`govendor sync` does not have a flag `-v`:

```
govendor sync
	Ensures the contents of the vendor folder matches the vendor file.
	Options:
		-n           dry run, print out action only
		-insecure    allow downloading over insecure connection
```

and thus fails with:
```
➜  ttn git:(develop) make dev-deps
govendor sync -v
Error: flag provided but not defined: -v
```